### ISSUE TITLE
bugi: calculateFarmland

### ISSUE THREAD

**Issue by durak** [tkt-biopeli/Biopeli#72]
StructureFactoryssä:
  calculateFarmLand (structure) {
    structure.ownedTiles.forEach(function (tmpTile) {
      structure.producer.producer.ownedFarmLand.push(tmpTile)
    }, this)
  }

-> kasvattaa uudestaan kokoa nollaamatta vanhaa, kutsutaan ilmeisesti ainaskin kun rakennettu myllyä pellon päälle

**Comment by iah1016** [comment]
Tämä on ok.
